world:
  map:
  num_agents:
  timestep:
  seed:
  num_envs:
  observation_config:
  control_input:
  render_mode:

car:
  num_beams:

logs:
  tensorboard_log:

params:
  device: 'cuda'
  learning_rate: 3e-4
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: None
  normalize_advantage: True
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: False
  sde_sample_freq: -1
  rollout_buffer_class: None
