world:
  seed: 42
  map: /Users/robbyligeralde/ese615/f1tenth_ppo/maps/easy # either single map or dir to be sampled from
  num_agents: 1
  num_envs: 1
  num_beams: 36 # number of lidar beams
  timestep: 0.01
  observation_config: 
    type: frenet_rl # need the nested dict for the observation config
  reset_config:
    type: rl_random_static
  control_input: ['speed', 'steering_angle']

car:
  #mu: 1.0489
  mu:
    min: 0.5
    max: 1.5
  C_Sf: 4.718
  C_Sr: 5.4562
  width: 0.31
  length: 0.58
  m: 3.74
  I: 0.04712
  h: 0.074
  v_min: -5.0
  v_max: 20.0
  a_max: 9.51
  s_min: -0.4189
  s_max: 0.4189
  v_switch: 7.319
  sv_min: -3.2
  sv_max: 3.2

ppo_params:
  recurrent: False
  device: cpu # actually faster on cpu, for some reason
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: True
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: False
  sde_sample_freq: -1

train_params:
  total_timesteps: 1000000
  log_interval: 1
  reset_num_timesteps: True
  progress_bar: False

log:
  log_tensorboard: False
  project_name: null # set null to disable wandb
