world:
  seed: 42
  map: levine # either single map or dir to be sampled from in domain randomization
  num_agents: 2
  num_envs:
    count: 8 # set -1 to use number of cpu cores
    type: dummy # subproc or dummy
  num_beams: 360 # number of lidar beams
  timestep: 0.01
  observation_config: 
    # lidar_conv, mlp, fremet_marl
    # if lidar_conv, uses dict{'lidar', 'odometry'} with respective cnn, mlp embeddings
    # if mlp, single mlp embedding
    # if frenet_marl, separate mlp for each key
    type: lidar_conv
  reset_config:
    type: rl_random_static
  control_input: ['speed', 'steering_angle']
  render_mode: null # set null to disable rendering: only for single env eval / debugging

rewards:
  normalize_observations: False
  normalize_rewards: False
  
  VELOCITY_REWARD_SCALE: 0.0
  TURN_SPEED_PENALTY: 0
  VEL_ACTION_CHANGE_PENALTY: 0
  STEER_ACTION_CHANGE_PENALTY: -0.05

  STAGNATION_PENALTY: -0.1
  STAGNATION_CUTOFF: 0.02
  
  HEADING_PENALTY: -1.0
  PROGRESS_WEIGHT: 100

  CRASH_CURRICULUM: 100000
  DECAY_INTERVAL: 100000
  DELTA_U_CURRICULUM: 1000000
  V_REF_CURRICULUM: 1000000

  MAX_CRASH_PENALTY: 1
  MILESTONE_REWARD: 10
  milestone: 0.1
  MILESTONE_INCREMENT: 0.1

  POSITION_WEIGHT: 1.0
  OVERTAKING_REWARD: 25.0


car:
  # dr_param_ex:
  #  min: x
  #  max: y
  mu: 0.6
  C_Sf: 4.718
  C_Sr: 5.4562
  width: 0.31
  length: 0.58
  m: 3.74
  I: 0.04712
  h: 0.074
  v_min: -4.0
  v_max: 4.0
  a_max: 6.34
  s_min: -0.4189
  s_max: 0.4189
  v_switch: 7.319
  sv_min: -3.2
  sv_max: 3.2

ppo_params:
  init_path: null # if resuming a run
  recurrent: False
  device: cpu # actually faster on cpu, for some reason
  learning_rate: 0.0001
  n_steps: 2048
  batch_size: 64
  n_epochs: 8
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.15
  clip_range_vf: null
  normalize_advantage: True
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: False
  sde_sample_freq: -1

train_params:
  total_timesteps: 1000
  save_interval: 1000 # set large to only save last policy
  log_interval: 1
  reset_num_timesteps: False
  progress_bar: False

log:
  log_tensorboard: False
  project_name: null # set null to disable wandb
  run_name: null
